### ISSUE TITLE
Member in Hieracy not showing

### ISSUE THREAD

**Issue by jamvandermeer** [SharePoint/sp-dev-gdpr-activity-hub#11]
Added 2 people to the Hierachy list, they are not showing in the Hierachy part
![gdprhierargy](https://user-images.githubusercontent.com/16414620/29170373-971c8230-7dd8-11e7-8de6-871303a798c9.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. You need to configure the Hierarchy source list in the web part properties.

**Comment by djontra** [comment]
Unlike "GDPR Dashboard" linked to Tasks, this does not solve the problem.

**Comment by djontra** [comment]
"GDPR Hierarchy web part" uses **Hierarchy** list for referencing to the **GDPRContactUser** list, which is not present after solution deployment. Please check why.

**Comment by jamvandermeer** [comment]
I did configure the Hierarchy, still no result :-(

**Comment by PaoloPia** [comment]
Did you get any error message while executing the provisioning? Do you mind to apply one more time the provisioning template? Just to see what happens ... thx.

**Comment by JoelFerreira1984** [comment]
Help anyone?

**Comment by tristian2** [comment]
bump,  everything else works for me, apart from the hierarchy viewer..

**Comment by tristian2** [comment]
i get this... the javascript is trying to call a list that is missing the column  <m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code>-2147024809, System.ArgumentException</m:code>
<m:message xml:lang="en-US">
Column 'GDPRContactRole' does not exist. It may have been deleted by another user. /sites/UoBGDPRTest-Group/Lists/GDPR Hierarchy
</m:message>
</m:error>

for a quick resolution i could add the column i guess
