### ISSUE TITLE
Access Denied 

### ISSUE THREAD

**Issue by DBR76** [SharePoint/sp-dev-gdpr-activity-hub#12]
I get Access Denied when applying provisioning template when running the script, As far as I know my credentials are correct and I am the owner of the site.

Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this
resource.
At C:\Users\...\Documents\sp-dev-gdpr-activity-hub-master\Scripts\Provision-GDPRActivityHub.ps1:70 char:9
         Apply-PnPProvisioningTemplate -Path .\GDPR-Activity-Hub-Infor ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
     FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Sometimes it happens that, when you create the Modern Site (GROUP#0) it takes a while to configure all the security settings. Can you try after a while to run the provisioning, and if it still fails, can you try to see where it fails (I mean, see if it fails during provisioning of fields, content types, lists or term groups)? If it fails during term groups, please double-check that your account has proper permissions to create the taxonomy. Thanks.

**Comment by nikskhubani** [comment]
Hi @DBR76 , this also could happen when you are NOT the term store administrator. I faced this issue too but when I saw, it was exactly throwing error when it was creating terms.. Give it a try :)

**Comment by PaoloPia** [comment]
Since I don't see any feedback on this, I assume you solved the issue and I will close this item. Thanks.

**Comment by SerbanTeron** [comment]
I have same issue and can not solve it:
Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this
resource.
At C:\Users\Serban Popa\Documents\sp-dev-gdpr-activity-hub\Scripts\Provision-GDPRActivityHub.ps1:70 char:9
+         Apply-PnPProvisioningTemplate -Path .\GDPR-Activity-Hub-Infor ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

Apply-PnPProvisioningTemplate : Expected hex 0x in '{0}'.
At C:\Users\Serban Popa\Documents\sp-dev-gdpr-activity-hub\Scripts\Provision-GDPRActivityHub.ps1:73 char:9
+         Apply-PnPProvisioningTemplate -Path .\GDPR-Activity-Hub-Workf ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], FormatException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by helloitsliam** [comment]
I have the same issue. My account is set as an Owner, Member, Site Collection Administrator and a Term Store Administrator too. Keeps returning the same error above

Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this resource.

![image](https://user-images.githubusercontent.com/4524182/35409334-e0e1320e-01df-11e8-8c43-232f6d8edbb2.png)

**Comment by Asmaro** [comment]
Did you ever solve this? I was having the same issue too.  I had to delete the style library in my modern team site in order to get it to work. However, in order to delete the style library I had to run this: 

•Open PowerShell as Admin
•Type in Connect-SPOService "https://-admin.sharepoint.com" -credential "admin full email address"
•Type in Set-SPOsite "SiteURL" -DenyAddAndCustomizePages 0

See this link for more information: 
https://sharepoint.stackexchange.com/questions/215190/site-collection-administrator-is-getting-access-denied-error-message-when-editin/215800

After doing that I stopped getting the access denied error but I am still getting the Exception on creating the CDN site collection. Can anyone help with that please/

**Comment by stanleyk1982** [comment]
Hello, 
same problem, can somebody help me ?
I am admin of tenant and andin of term store

PS C:\gdpr\Scripts> .\Provision-GDPRActivityHub.ps1 -GroupSiteUrl "https://alfacexample.sharepoint.com/sites/gdpr" `
>>                                 -Credentials $credentials `
>>                                 -ConfigureCDN `
>>                                 -CDNSiteName "cdnsite" `
>>                                 -CDNLibraryName "cdnlibrary"
>>
Creating artifacts on target site https://alfacexample.sharepoint.com/sites/gdpr
Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this resourc
e.
At C:\gdpr\Scripts\Provision-GDPRActivityHub.ps1:70 char:9
+         Apply-PnPProvisioningTemplate -Path .\GDPR-Activity-Hub-Infor ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

WARNING: Workflow Subscription 'Data Breach Management' already exists. It will be updated.
WARNING: Workflow Subscription 'External Data Processing' already exists. It will be updated.
WARNING: Workflow Subscription 'Request to Access Personal Data Management' already exists. It will be updated.
Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this resourc
e.
At C:\gdpr\Scripts\Provision-GDPRActivityHub.ps1:73 char:9
+         Apply-PnPProvisioningTemplate -Path .\GDPR-Activity-Hub-Workf ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

Configuring the Office 365 CDN Settings
WARNING: Execute-PnPQuery has been deprecated. Use Invoke-PnPQuery instead.
Creating CDN Site Collection
Exception occurred!
Exception Type: System.Management.Automation.ParameterBindingException
Exception Message: A parameter cannot be found that matches parameter name 'RemoveDeletedSite'.
PS C:\gdpr\Scripts>


it fail when start make list instances data rows

**Comment by SP-lbe** [comment]
Same here get access denied error trying to apply apply-pnpprovisioningtemplate to a communication site with HUB connection,
Last log item is:
powershell_ise.exe Information: 0 : 2019-03-05 11:19:59.9616	[Provisioning]	[12]	[Information]	MessagesDelegate registered	1ms	6d9cd705-3e06-472c-9910-5ff23373b7b5

and then get the error message:
Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this resource.
At line:1 char:1
+ Apply-PnPProvisioningTemplate C:\temp\Export-PnP-Template\template.xml ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
