### ISSUE TITLE
Adding Tasks calendar view to the group page (GDPR Dashboard)

### ISSUE THREAD

**Issue by djontra** [SharePoint/sp-dev-gdpr-activity-hub#13]
While it is possible to select specific view of the Tasks web part when creating a "regular" page (...GDPRActivityHub/SitePages/Forms/ByAuthor.aspx -> New),
this functionality is not allowed when editing GDPR Dashboard group page:
Tasks can be added as either "Highlighted content" or custom "GDPR Dashboard" web part. Neither allows for the particular view to be selected.

Any suggestions?

**Comment by PaoloPia** [comment]
No I'm sorry. Maybe you need to create a custom client-side web part to render the custom view that you are looking for.
