### ISSUE TITLE
CDN issue

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-gdpr-activity-hub#16]
Hi, I tried couple of times on different tenants and different site collection but I am getting the same issue. I am able to reach till end but finally when I add a new webpart (Create Event) to any of the page, I get following CDN error; 

[SPLoaderError.loadComponentError]:
***Failed to load component "d67d6088-e294-4a23-af02-c4ea8783c23f" (GdprInsertEventWebPart).
Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/tenant.sharepoint.com/sites/CDN/CDNFiles/GDPRActivityHub/gdprstarterkit-gdprinsertrequeststrings_en-us_3a374bd4fecd98b5af22dc9a8072d8b6.js' for resource 'gdprInsertRequestStrings' in component 'd67d6088-e294-4a23-af02-c4ea8783c23f' (GdprInsertEventWebPart). There was a problem in the server.

***INNERERROR:
***Failed to load URL 'https://publiccdn.sharepointonline.com/tenant.sharepoint.com/sites/CDN/CDNFiles/GDPRActivityHub/gdprstarterkit-gdprinsertrequeststrings_en-us_3a374bd4fecd98b5af22dc9a8072d8b6.js' for resource 'gdprInsertRequestStrings' in component 'd67d6088-e294-4a23-af02-c4ea8783c23f' (GdprInsertEventWebPart). There was a problem in the server.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-18.020/sp-pages-assembly_en-us_979736c90443c68cb015418392782008.js:364:12139)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-18.020/sp-pages-assembly_en-us_979736c90443c68cb015418392782008.js:918:19835)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-18.020/sp-pages-assembly_en-us_979736c90443c68cb015418392782008.js:918:12590)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-18.020/sp-pages-assembly_en-us_979736c90443c68cb015418392782008.js:918:8659)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-08-18.020/sp-pages-assembly_en-us_979736c90443c68cb015418392782008.js:918:116163
    at <anonymous>

Any comment?

**Comment by nikskhubani** [comment]
Also, I made sure the document library is there and it has the file which is giving error. And when I do 

Get-SPOTenant | fl *cdn*

I get following;


PublicCdnEnabled          : True
PublicCdnAllowedFileTypes : CSS,EOT,GIF,ICO,JPEG,JPG,JS,MAP,PNG,SVG,TTF,WOFF
PublicCdnOrigins          : {134600545c3743abc6b06b3e78720187bffda36cdb43d6675fef52232902a67386d444a9}

Which seems OK I feel...

**Comment by PerOve** [comment]
I see that the PublicCdnOrigins are different with my tenant.
"
Get-SPOTenantCdnOrigins -CdnType Public
*/MASTERPAGE
*/STYLE LIBRARY
SITES/CDN/CDNFILES
"

**Comment by PerOve** [comment]
I also added JSON to the PublicCdnAllowedFileTypes (Do not know if it is needed, but since there were json files in the CDNFiles folder, I thought it may be needed.

**Comment by PerOve** [comment]
I know what is wrong with your files. It is not the CDN.
You url:
'https://publiccdn.sharepointonline.com/tenant.sharepoint.com/sites/CDN/CDNFiles/GDPRActivityHub/...

The part with tenant.sharepoint.com should have the name of your tenant instead of the word tenant.

You can find the fix for the files in this pull request:
https://github.com/SharePoint/sp-dev-gdpr-activity-hub/pull/14/files

Change your files and rebuild by running the gulp tasks.
Upload the files to CDN and the App again

Now it should work after a while. :)

**Comment by nikskhubani** [comment]
Hi @PerOve , Thank you very much. that fixed the issue, finally I was able to run full script without any error :)

**Comment by PaoloPia** [comment]
Thank you @PerOve for supporting the community. I will close this item, as it is solved.
