### ISSUE TITLE
Folders missing in the zip file deploy package.

### ISSUE THREAD

**Issue by PerOve** [SharePoint/sp-dev-gdpr-activity-hub#17]
I downloaded the zip file and ran the .ps1 file from the script folder.
The 'GDPRStarterKit\temp\deploy' folder does not exist, resulting in error 1.
The 'GDPRStarterKit\sharepoint\solution\gdpr-starter-kit.sppkg' folder does not exist, resulting in error 2.

Error 1:
Uploading SPFx assets to the CDN
dir : Cannot find path 'C:\code\gdpractivityhub\GDPRStarterKit\temp\deploy' because it does not exist.
At C:\code\gdpractivityhub\Scripts\Provision-GDPRActivityHub.ps1:131 char:32
+ ...          foreach ($file in (dir ..\GDPRStarterKit\temp\deploy -File))
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\code\gdpract...Kit\temp\deploy:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 

Error 2:
Get-Item : Cannot find path 'C:\code\gdpractivityhub\GDPRStarterKit\sharepoint\solution\gdpr-starter-kit.sppkg' because it does not exist.
At C:\code\gdpractivityhub\Scripts\Provision-GDPRActivityHub.ps1:153 char:23
+ ... ppkgPath = (Get-Item -Path "..\GDPRStarterKit\sharepoint\solution\gdp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\code\gdpract...arter-kit.sppkg:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

**Comment by PerOve** [comment]
Found the following in my PowerShell script runlog:
Building SPFx package and bundling
[15:58:44] Local gulp not found in C:\code\gdpractivityhub\GDPRStarterKit
[15:58:44] Try running: npm install gulp
[15:58:46] Local gulp not found in C:\code\gdpractivityhub\GDPRStarterKit
[15:58:46] Try running: npm install gulp
[15:58:47] Local gulp not found in C:\code\gdpractivityhub\GDPRStarterKit
[15:58:48] Try running: npm install gulp
[15:58:49] Local gulp not found in C:\code\gdpractivityhub\GDPRStarterKit
[15:58:49] Try running: npm install gulp
Uploading SPFx assets to the CDN

There is no local gulp installed in the folder. 
Add this step to the install guide?

**Comment by nikskhubani** [comment]
You will have to run that command in local folder 

You can do following
in command prompt navigate to "C:\code\gdpractivityhub\GDPRStarterKit" using cd "C:\code\gdpractivityhub\GDPRStarterKit"

Execute following

npm install gulp
npm install @microsoft/generator-sharepoint

That should fix above issue, However I faced few more detailed errors and to fix that I had to run following commands;

npm install --save-dev
npm cache clean
npm i

And everything  worked :)

Now, I am stuck at another issue regarding CDN. If you can fix that, let me know :)

**Comment by PerOve** [comment]
Thanks, that worked better.
I still got an error when running gulp update-manifest "$CDNSiteAssetsFullUrl" (see error below)

There were no update-manifest task in my gulpfile.js.
But I found it in gulp-update-manifest.js file. 
So I copied it over  to gulpfile.js and then it ran.

It modifies the URL to the CDN. Maybe that is your problem?

--
Build target: DEBUG
[12:44:31] Using gulpfile C:\code\gdpractivityhub\GDPRStarterKit\gulpfile.js
[12:44:31] Task 'update-manifest' is not in your gulpfile
[12:44:31] Please check the documentation for proper gulpfile formatting
[12:44:31] Task 'update-manifest' is not in your gulpfile
[12:44:31] Please check the documentation for proper gulpfile formatting
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1--

**Comment by PerOve** [comment]
This pull request will solve this issue:

https://github.com/SharePoint/sp-dev-gdpr-activity-hub/pull/14/files
