### ISSUE TITLE
Data Limit (SharePoint list)

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-gdpr-activity-hub#18]
@PaoloPia , what do you think should be suggested limit of data we can put in Events and Request list. If we are talking about enterprises, there could be millions of records they might log, do you recommend SharePoint list is good for it?

**Comment by PaoloPia** [comment]
Hi @nikskhubani,
I don't recommend to use SharePoint to store data for enterprises. I rather suggest (as you can read here: https://github.com/SharePoint/sp-dev-gdpr-activity-hub/blob/master/Documentation/Customization.md#data-provider-customization) to create a custom data persistence layer, which for example uses SQL Database on Azure.
