### ISSUE TITLE
failed to bundle and package solution by error message "TypeError: Cannot read property 'readCommentedJsonFile' of undefined"

### ISSUE THREAD

**Issue by farawayplace613** [SharePoint/sp-dev-gdpr-activity-hub#21]
PS E:\spfx\githubdemos\GDPR\sp-dev-gdpr-activity-hub\GDPRStarterKit> gulp bundle --ship
Build target: SHIP
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
[14:04:52] Error - Unknown
 undefined
[14:04:52] ==================[ Finished ]==================
[14:04:53] Project gdpr-starter-kit version: 0.0.1
[14:04:53] Build tools version: 2.10.0
[14:04:53] Node version: v6.11.1
[14:04:53] Total duration: 2.08 s
[14:04:53] Task errors: 2
PS E:\spfx\githubdemos\GDPR\sp-dev-gdpr-activity-hub\GDPRStarterKit> gulp package-solution --ship
Build target: SHIP
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
[14:23:17] Error - Unknown
 undefined
[14:23:18] ==================[ Finished ]==================
[14:23:18] Project gdpr-starter-kit version: 0.0.1
[14:23:18] Build tools version: 2.10.0
[14:23:18] Node version: v6.11.1
[14:23:18] Total duration: 2.31 s
[14:23:18] Task errors: 2

**Comment by jamvandermeer** [comment]
Has todo with the dev. environment. goto gdrpstarterkit and execute
>npm install --save

**Comment by farawayplace613** [comment]
Hi Hans,

Thanks you very much for your great help indeed.

But, I did run this command before I'm trying to package it.

I run the command again, looks like it will skip it(only two warning) as it
have installed,

PS E:\spfx\githubdemos\GDPR\sp-dev-gdpr-activity-hub\GDPRStarterKit> npm
install --save
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})

Thanks,
Abraham Cheng

**Comment by farawayplace613** [comment]
download the source code again, then run the command " npm
install --save", then package command works fine
