### ISSUE TITLE
Setup / build script isn't correct as gulpfile-update-manifest.js isn't correctly included

### ISSUE THREAD

**Issue by biste5** [SharePoint/sp-dev-gdpr-activity-hub#22]
A small bug in the setup / build of the client solution.

`gulpfile.js` should include the following line
`require('./gulpfile-update-manifest.js');`

or else the command 'gulp update-manifest' to set the correct CDN URL won't work.

Refer also to this documentation:
https://github.com/SharePoint/sp-dev-build-extensions/tree/master/gulp-tasks/update-manifest

**Comment by biste5** [comment]
PR is merged to 'dev' branch. When merged into 'master' we can close this issue

**Comment by PaoloPia** [comment]
Merged!
