### ISSUE TITLE
Save button enabled but not working

### ISSUE THREAD

**Issue by jamvandermeer** [SharePoint/sp-dev-gdpr-activity-hub#5]
When I fill in all the fields in a new rquest form the Save button is enabled but after clicking on it notheting happens, same for the other forms

**Comment by djontra** [comment]
Have you tried editing the page (.../sites/GDPRActivityHub/SitePages/GDPR%20Insert%20Event.aspx?Mode=Edit) and pointing to the Requests/Events list?

**Comment by jamvandermeer** [comment]
Yes and then I can Add an Incident. but a strange column name data_x0020_breach_x0020. And the task list is empty

![image](https://user-images.githubusercontent.com/16414620/29117631-40174896-7cff-11e7-80cc-d507fefd4ddf.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Can you expand a little bit more about the column. Where do you see it? What is the problem with it? Thanks.

**Comment by jamvandermeer** [comment]
See the Screen shot:  Data_x0020_breach_x0020  the _x0020 should not be there

**Comment by jamvandermeer** [comment]
Any news on why the Save button isn't working?

**Comment by jamvandermeer** [comment]
this is in de debugger
Fetch)GET - https://softlake.sharepoint.com/sites/AVG/_api/web/lists('undefined')?$select=ListItemEntityTypeFullName

**Comment by PaoloPia** [comment]
Thus, I guess the issue was that the target list was not configured.
