### ISSUE TITLE
GDPR Insert Event - Target List bug

### ISSUE THREAD

**Issue by djontra** [SharePoint/sp-dev-gdpr-activity-hub#6]
FYI, seems that this page does not point to Events list by default, probably just a slip.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. When you create the page and you add the client-side web part, you need to manually configure the target list. Unfortunately we still don't have the capability to automate the provisioning of that setting. However, we're working on it with PnP and pretty soon it will be possible to automate that part of the setup process. Thanks.

**Comment by PaoloPia** [comment]
Since I don't see any feedback on this, I assume you solved the issue and I will close this item. Thanks.
