### ISSUE TITLE
Access to teh resource forbidden opening PowerBi

### ISSUE THREAD

**Issue by jamvandermeer** [SharePoint/sp-dev-gdpr-activity-hub#7]
When I try to open the gdpr.pbit file and enter the SharePoint site. It gives me an error Access to the resource is forbidden. I tried other Windows user credentials and the troubleshoot tips but it gives me the same error. I have a PowerBi - pro license. Whem I use Microsoft account and login with office365 account I get this:

![image](https://user-images.githubusercontent.com/16414620/29117042-09a70956-7cfd-11e7-970d-c53d6115ee0e.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Do you have any data in the source lists? Sometimes it fails just because you're missing any data in the data source. Please let me know. Thanks.

**Comment by jamvandermeer** [comment]
I can't but data in becuase the Save button is not working when I add something :-(

**Comment by PaoloPia** [comment]
Ok, so I will connect this issue with the other one #5 - Let me know if by adding data to the lists, now you can see the insights from the dashboard. Thanks.

**Comment by Theoneandonly8** [comment]
Hi,

@PaoloPia, I am having an error while trying to setup the GDPR Activity hub and will deeply appreciate your help. 

At the end of the setup guide, when you are asked to click the 'Publish' button to publish the report it gives an error: The column id of the table was not found

I think I need to upload some sample/real data in this phase? But I am unsure how to upload it and what to upload to get it working? Please guide me to the right direction?

Best Regards
