### ISSUE TITLE
Lookup fields for existing Taxonomy Term Sets

### ISSUE THREAD

**Issue by djontra** [SharePoint/sp-dev-gdpr-activity-hub#8]
How much hassle would it be to implement look-up for the fields related to the Taxonomy?, e.g.:
- Insert Request: Breach Type, Severity...
- Insert Event: Consent Type, Risk Type...

Now, very impractical for non-admin users.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We will think about this possibility. The only potential issue is that in case of too many possible values the lookup will become not very usable ... but as I said, we will think about it. Moreover, it is an open source project, so if you already have a suggested change to submit, please feel free to make a Pull Request. Thanks.

**Comment by djontra** [comment]
Thanks for your reply.
I'm not sure what kind of lookup you had in mind, but if some kind of drop-down menu might not be suitable for long lists, default Sharepoint list item edit lookup, which opens a lookup window, certainly would be fine.
No changes yet, we'll try to contribute further on.

**Comment by PaoloPia** [comment]
Right now, there is a kind of intellisense while filling the text fields of taxonomy fields. Isn't it enough?

**Comment by PaoloPia** [comment]
Since I don't see any feedback on this, I assume you solved the issue and I will close this item. Thanks.
